augmentation:
  brightness_contrast: 0.2
  cutmix_alpha: 1.0
  elastic_transform: true
  horizontal_flip: 0.5
  mixup_alpha: 0.2
  rotation: 15
data:
  batch_size: 16
  dataset_path: data/chest_xray
  img_size: 224
  mean:
  - 0.485
  - 0.456
  - 0.406
  num_workers: 4
  std:
  - 0.229
  - 0.224
  - 0.225
  test_split: 0.1
  train_split: 0.8
  val_split: 0.1
evaluation:
  metrics:
  - accuracy
  - precision
  - recall
  - f1
  - auc
  save_attention_maps: true
  save_predictions: true
loss:
  alpha: 0.25
  gamma: 2.0
  label_smoothing: 0.1
  type: focal
model:
  dropout: 0.1
  embed_dim: 512
  img_size: 224
  mlp_ratio: 4.0
  name: MedicalViT
  num_classes: 2
  num_heads: 8
  num_layers: 12
  patch_size: 16
paths:
  log_path: logs/
  model_save_path: models/
  results_path: results/
training:
  early_stopping_patience: 20
  epochs: 20
  learning_rate: 0.0001
  save_best_only: true
  scheduler: cosine
  warmup_epochs: 5
  weight_decay: 0.01
